# These are supported funding model platforms

## Supported
github: File-New-Project

## Currently unsupported
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
custom:
