import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(2B278740-717F-4D43-987D-05BA8EAC7943),
    pointer_default(unique)
]
interface IEndpointNotificationCallback : IUnknown
{
    HRESULT OnVolumeChanged(float volume);
};

[
    object,
    uuid(68CDB936-6903-48E5-BB36-7EF434F28B61),
    pointer_default(unique)
]
interface IEarTrumpetVolumeCallback : IUnknown
{
    HRESULT OnVolumeChanged(float volume);
};

[
    object,
    uuid(0AC96DA4-337E-4975-ACD7-082E0B85B3C6),
    pointer_default(unique)
]
interface IControlChangeCallback : IUnknown
{
    HRESULT OnVolumeChanged(LPCWSTR deviceId, float volume);
};