import "oaidl.idl";
import "ocidl.idl";
import "IControlChangeCallback.idl";
[
    object,
    uuid(265E0961-8265-46F0-A062-173B8CB3CDC6),
    pointer_default(unique)
]
interface IControlChangeHandler : IUnknown
{
    HRESULT RegisterVolumeChangedCallback(IControlChangeCallback* callback);
};