import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(2B278740-717F-4D43-987D-05BA8EAC7943),
    pointer_default(unique)
]
interface IEndpointNotificationCallback : IUnknown
{
    HRESULT OnVolumeChanged(float volume);
};