import "oaidl.idl";
import "ocidl.idl";
import "IEndpointNotificationCallback.idl";

[
    object,
    uuid(AAFE7CFC-E840-4C59-B055-9F1D2D01C68F),
    pointer_default(unique)
]
interface IEndpointNotificationHandler : IUnknown
{
    HRESULT RegisterVolumeChangeHandler(IEndpointNotificationCallback*);
};