import "oaidl.idl";
import "ocidl.idl";
import "endpointvolume.idl";
import "audiopolicy.idl";

// We use the below library statement to enable the MIDL compiler to output a TLB with 
// arbitrary interfaces that don't appear in mmdeviceapi.idl's library statement.

[
	uuid(BA5C648E-F969-4D61-BCE7-1262B9B73775),
	version(1.0),
	helpstring("Sound Control API Type Library 1.0")
]
library SoundControlAPILib
{
	interface IAudioSessionManager2;
	interface IAudioEndpointVolume;
	interface IAudioMeterInformation;
	interface IAudioSessionControl2;
};