//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarTrumpet_Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarTrumpet_Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and then.
        /// </summary>
        public static string ActionAdditionalText {
            get {
                return ResourceManager.GetString("ActionAdditionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string ActionVerbText {
            get {
                return ResourceManager.GetString("ActionVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {App} on {Device} {Option}.
        /// </summary>
        public static string AppEventTriggerDescribeFormatText {
            get {
                return ResourceManager.GetString("AppEventTriggerDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an app session is (added, removed, plays sound, ...).
        /// </summary>
        public static string AppEventTriggerDescriptionText {
            get {
                return ResourceManager.GetString("AppEventTriggerDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is added.
        /// </summary>
        public static string AudioAppEventKindAddedText {
            get {
                return ResourceManager.GetString("AudioAppEventKindAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begins playing sound.
        /// </summary>
        public static string AudioAppEventKindBeginPlaySoundText {
            get {
                return ResourceManager.GetString("AudioAppEventKindBeginPlaySoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stops playing sound.
        /// </summary>
        public static string AudioAppEventKindEndsPlaySoundText {
            get {
                return ResourceManager.GetString("AudioAppEventKindEndsPlaySoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is muted.
        /// </summary>
        public static string AudioAppEventKindMutedText {
            get {
                return ResourceManager.GetString("AudioAppEventKindMutedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is removed.
        /// </summary>
        public static string AudioAppEventKindRemovedText {
            get {
                return ResourceManager.GetString("AudioAppEventKindRemovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is unmuted.
        /// </summary>
        public static string AudioAppEventKindUnmutedText {
            get {
                return ResourceManager.GetString("AudioAppEventKindUnmutedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is added.
        /// </summary>
        public static string AudioDeviceEventKindAddedText {
            get {
                return ResourceManager.GetString("AudioDeviceEventKindAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to becomes default.
        /// </summary>
        public static string AudioDeviceEventKindBecomesDefaultText {
            get {
                return ResourceManager.GetString("AudioDeviceEventKindBecomesDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaves default.
        /// </summary>
        public static string AudioDeviceEventKindLeavesDefaultText {
            get {
                return ResourceManager.GetString("AudioDeviceEventKindLeavesDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is removed.
        /// </summary>
        public static string AudioDeviceEventKindRemovedText {
            get {
                return ResourceManager.GetString("AudioDeviceEventKindRemovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string BoolFalseText {
            get {
                return ResourceManager.GetString("BoolFalseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string BoolTrueText {
            get {
                return ResourceManager.GetString("BoolTrueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string ConditionAdditionalText {
            get {
                return ResourceManager.GetString("ConditionAdditionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string ConditionVerbText {
            get {
                return ResourceManager.GetString("ConditionVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I click a context menu item in EarTrumpet.
        /// </summary>
        public static string ContextMenuTriggerCurrentDescriptionText {
            get {
                return ResourceManager.GetString("ContextMenuTriggerCurrentDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a context menu item in EarTrumpet.
        /// </summary>
        public static string ContextMenuTriggerDescriptionText {
            get {
                return ResourceManager.GetString("ContextMenuTriggerDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default playback device {Option} {Device}.
        /// </summary>
        public static string DefaultDeviceConditionDescribeFormatText {
            get {
                return ResourceManager.GetString("DefaultDeviceConditionDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the default playback device (is, is not).
        /// </summary>
        public static string DefaultDeviceConditionDescriptionText {
            get {
                return ResourceManager.GetString("DefaultDeviceConditionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default playback device.
        /// </summary>
        public static string DefaultPlaybackDeviceText {
            get {
                return ResourceManager.GetString("DefaultPlaybackDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Device} {Option}.
        /// </summary>
        public static string DeviceEventTriggerDescribeFormatText {
            get {
                return ResourceManager.GetString("DeviceEventTriggerDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an audio device is (added, removed, becomes or leaves default).
        /// </summary>
        public static string DeviceEventTriggerDescriptionText {
            get {
                return ResourceManager.GetString("DeviceEventTriggerDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shuts down.
        /// </summary>
        public static string EarTrumpetEventKindShutdownText {
            get {
                return ResourceManager.GetString("EarTrumpetEventKindShutdownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts up.
        /// </summary>
        public static string EarTrumpetEventKindStartupText {
            get {
                return ResourceManager.GetString("EarTrumpetEventKindStartupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit actions and hotkeys.
        /// </summary>
        public static string EditActionsAndHotkeysText {
            get {
                return ResourceManager.GetString("EditActionsAndHotkeysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet {Option}.
        /// </summary>
        public static string EventTriggerDescribeFormatText {
            get {
                return ResourceManager.GetString("EventTriggerDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When EarTrumpet is started or stopped.
        /// </summary>
        public static string EventTriggerDescriptionText {
            get {
                return ResourceManager.GetString("EventTriggerDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every app.
        /// </summary>
        public static string EveryAppText {
            get {
                return ResourceManager.GetString("EveryAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground app.
        /// </summary>
        public static string ForegroundAppText {
            get {
                return ResourceManager.GetString("ForegroundAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Hotkey} is pressed.
        /// </summary>
        public static string HotkeyTriggerDescribeFormatText {
            get {
                return ResourceManager.GetString("HotkeyTriggerDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a hotkey is pressed.
        /// </summary>
        public static string HotkeyTriggerDescriptionText {
            get {
                return ResourceManager.GetString("HotkeyTriggerDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke additional actions.
        /// </summary>
        public static string InvokeAdditionalCommandsText {
            get {
                return ResourceManager.GetString("InvokeAdditionalCommandsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My actions.
        /// </summary>
        public static string MyActionsText {
            get {
                return ResourceManager.GetString("MyActionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New action.
        /// </summary>
        public static string NewActionText {
            get {
                return ResourceManager.GetString("NewActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (optional).
        /// </summary>
        public static string OptionalText {
            get {
                return ResourceManager.GetString("OptionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback: {0}.
        /// </summary>
        public static string PlaybackDeviceFormatStringText {
            get {
                return ResourceManager.GetString("PlaybackDeviceFormatStringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Text} {Option}.
        /// </summary>
        public static string ProcessConditionDescribeFormatText {
            get {
                return ResourceManager.GetString("ProcessConditionDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a process is (running, not running).
        /// </summary>
        public static string ProcessConditionDescriptionText {
            get {
                return ResourceManager.GetString("ProcessConditionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (enter a process name).
        /// </summary>
        public static string ProcessConditionEmptyText {
            get {
                return ResourceManager.GetString("ProcessConditionEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name (e.g. notepad).
        /// </summary>
        public static string ProcessConditionPromptText {
            get {
                return ResourceManager.GetString("ProcessConditionPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts.
        /// </summary>
        public static string ProcessEventKindStartsText {
            get {
                return ResourceManager.GetString("ProcessEventKindStartsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stops.
        /// </summary>
        public static string ProcessEventKindStopsText {
            get {
                return ResourceManager.GetString("ProcessEventKindStopsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not running.
        /// </summary>
        public static string ProcessStateKindNotRunningText {
            get {
                return ResourceManager.GetString("ProcessStateKindNotRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is running.
        /// </summary>
        public static string ProcessStateKindRunningText {
            get {
                return ResourceManager.GetString("ProcessStateKindRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Text} {Option}.
        /// </summary>
        public static string ProcessTriggerDescribeFormatText {
            get {
                return ResourceManager.GetString("ProcessTriggerDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name (e.g. notepad).
        /// </summary>
        public static string ProcessTriggerDescriptonPromptText {
            get {
                return ResourceManager.GetString("ProcessTriggerDescriptonPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a process starts or stops.
        /// </summary>
        public static string ProcessTriggerDescriptonText {
            get {
                return ResourceManager.GetString("ProcessTriggerDescriptonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording: {0}.
        /// </summary>
        public static string RecordingDeviceFormatStringText {
            get {
                return ResourceManager.GetString("RecordingDeviceFormatStringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveText {
            get {
                return ResourceManager.GetString("RemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (required).
        /// </summary>
        public static string RequiredText {
            get {
                return ResourceManager.GetString("RequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {Option1} to {Option2}.
        /// </summary>
        public static string SetAdditionalSettingsActionDescribeFormatText {
            get {
                return ResourceManager.GetString("SetAdditionalSettingsActionDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set additional EarTrumpet settings.
        /// </summary>
        public static string SetAdditionalSettingsActionDescriptionText {
            get {
                return ResourceManager.GetString("SetAdditionalSettingsActionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute or unmute an app.
        /// </summary>
        public static string SetAppMuteActionDescriptionText {
            get {
                return ResourceManager.GetString("SetAppMuteActionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Option} volume to {Volume} for {App} on {Device}.
        /// </summary>
        public static string SetAppVolumeActionDescribeSetVolumeFormatText {
            get {
                return ResourceManager.GetString("SetAppVolumeActionDescribeSetVolumeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {Option} for {App} on {Device}.
        /// </summary>
        public static string SetAppVolumeActionDescribeValueFormatText {
            get {
                return ResourceManager.GetString("SetAppVolumeActionDescribeValueFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set an app volume.
        /// </summary>
        public static string SetAppVolumeActionDescriptionText {
            get {
                return ResourceManager.GetString("SetAppVolumeActionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {Device} as playback default.
        /// </summary>
        public static string SetDefaultDeviceActionDescribeFormatText {
            get {
                return ResourceManager.GetString("SetDefaultDeviceActionDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the default playback device.
        /// </summary>
        public static string SetDefaultDeviceActionDescriptionText {
            get {
                return ResourceManager.GetString("SetDefaultDeviceActionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute or unmute a device.
        /// </summary>
        public static string SetDeviceMuteActionDescriptionText {
            get {
                return ResourceManager.GetString("SetDeviceMuteActionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Option} volume to {Volume} for {Device}.
        /// </summary>
        public static string SetDeviceVolumeActionDescribeSetVolumeFormatText {
            get {
                return ResourceManager.GetString("SetDeviceVolumeActionDescribeSetVolumeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {Option} on {Device}.
        /// </summary>
        public static string SetDeviceVolumeActionDescribeValueFormatText {
            get {
                return ResourceManager.GetString("SetDeviceVolumeActionDescribeValueFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a device volume.
        /// </summary>
        public static string SetDeviceVolumeActionDescriptionText {
            get {
                return ResourceManager.GetString("SetDeviceVolumeActionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the EarTrumpet app theme.
        /// </summary>
        public static string SetThemeActionDescriptionText {
            get {
                return ResourceManager.GetString("SetThemeActionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set variable &apos;{Text}&apos; to {Option}.
        /// </summary>
        public static string SetVariableActionDescribeFormatText {
            get {
                return ResourceManager.GetString("SetVariableActionDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a local variable.
        /// </summary>
        public static string SetVariableActionDescriptionText {
            get {
                return ResourceManager.GetString("SetVariableActionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a variable name (e.g. IsInGameMode).
        /// </summary>
        public static string SetVariableActionPromptText {
            get {
                return ResourceManager.GetString("SetVariableActionPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decrement.
        /// </summary>
        public static string StreamActionKindDecrement5Text {
            get {
                return ResourceManager.GetString("StreamActionKindDecrement5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to increment.
        /// </summary>
        public static string StreamActionKindIncrement5Text {
            get {
                return ResourceManager.GetString("StreamActionKindIncrement5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mute.
        /// </summary>
        public static string StreamActionKindMuteText {
            get {
                return ResourceManager.GetString("StreamActionKindMuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        public static string StreamActionKindSetVolumeText {
            get {
                return ResourceManager.GetString("StreamActionKindSetVolumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toggle mute.
        /// </summary>
        public static string StreamActionKindToggleMuteText {
            get {
                return ResourceManager.GetString("StreamActionKindToggleMuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unmute.
        /// </summary>
        public static string StreamActionKindUnuteText {
            get {
                return ResourceManager.GetString("StreamActionKindUnuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toggle.
        /// </summary>
        public static string ToggleText {
            get {
                return ResourceManager.GetString("ToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string TriggerAdditionalText {
            get {
                return ResourceManager.GetString("TriggerAdditionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string TriggerVerbText {
            get {
                return ResourceManager.GetString("TriggerVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        public static string ValueComparisonKindIsNotText {
            get {
                return ResourceManager.GetString("ValueComparisonKindIsNotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string ValueComparisonKindIsText {
            get {
                return ResourceManager.GetString("ValueComparisonKindIsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{Text}&apos; is {Option}.
        /// </summary>
        public static string VariableConditionDescribeFormatText {
            get {
                return ResourceManager.GetString("VariableConditionDescribeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a local variable is (true or false).
        /// </summary>
        public static string VariableConditionDescriptionText {
            get {
                return ResourceManager.GetString("VariableConditionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (enter a variable name).
        /// </summary>
        public static string VariableConditionEmptyText {
            get {
                return ResourceManager.GetString("VariableConditionEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a variable name (e.g. IsInGameMode).
        /// </summary>
        public static string VariableConditionPromptText {
            get {
                return ResourceManager.GetString("VariableConditionPromptText", resourceCulture);
            }
        }
    }
}
