//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarTrumpet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarTrumpet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {Name} add-on.
        /// </summary>
        public static string AboutThisAddonText {
            get {
                return ResourceManager.GetString("AboutThisAddonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New From Selected.
        /// </summary>
        public static string AddFromExistingMidiControlButtonText {
            get {
                return ResourceManager.GetString("AddFromExistingMidiControlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddMidiControlButtonText {
            get {
                return ResourceManager.GetString("AddMidiControlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string AddonNameText {
            get {
                return ResourceManager.GetString("AddonNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows Settings.
        /// </summary>
        public static string AddonUninstallButtonText {
            get {
                return ResourceManager.GetString("AddonUninstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This add-on can be removed using the Windows Settings app..
        /// </summary>
        public static string AddonUninstallDescriptionText {
            get {
                return ResourceManager.GetString("AddonUninstallDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string AddonUninstallTitle {
            get {
                return ResourceManager.GetString("AddonUninstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *All Devices*.
        /// </summary>
        public static string AllAudioDevicesSelectionText {
            get {
                return ResourceManager.GetString("AllAudioDevicesSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Mute.
        /// </summary>
        public static string ApplicationMute {
            get {
                return ResourceManager.GetString("ApplicationMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Selection.
        /// </summary>
        public static string ApplicationSelection {
            get {
                return ResourceManager.GetString("ApplicationSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Volume.
        /// </summary>
        public static string ApplicationVolume {
            get {
                return ResourceManager.GetString("ApplicationVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{Volume}% volume - {Name}&quot;.
        /// </summary>
        public static string AppOrDeviceFormatAccessibleText {
            get {
                return ResourceManager.GetString("AppOrDeviceFormatAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Muted - {Name}&quot;.
        /// </summary>
        public static string AppOrDeviceMutedFormatAccessibleText {
            get {
                return ResourceManager.GetString("AppOrDeviceMutedFormatAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string AppsListAccessibleText {
            get {
                return ResourceManager.GetString("AppsListAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Device.
        /// </summary>
        public static string AudioDevice {
            get {
                return ResourceManager.GetString("AudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Mute.
        /// </summary>
        public static string AudioDeviceMute {
            get {
                return ResourceManager.GetString("AudioDeviceMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Volume.
        /// </summary>
        public static string AudioDeviceVolume {
            get {
                return ResourceManager.GetString("AudioDeviceVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonAccessibleText {
            get {
                return ResourceManager.GetString("CloseButtonAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse to show only the default playback device.
        /// </summary>
        public static string CollapseAccessibleText {
            get {
                return ResourceManager.GetString("CollapseAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ContextMenuExitTitle {
            get {
                return ResourceManager.GetString("ContextMenuExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playback devices found.
        /// </summary>
        public static string ContextMenuNoDevices {
            get {
                return ResourceManager.GetString("ContextMenuNoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string ContextMenuSendFeedback {
            get {
                return ResourceManager.GetString("ContextMenuSendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string ControllerTypeButtonText {
            get {
                return ResourceManager.GetString("ControllerTypeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Potentiometer.
        /// </summary>
        public static string ControllerTypeLinearPotentiometerText {
            get {
                return ResourceManager.GetString("ControllerTypeLinearPotentiometerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotary Encoder.
        /// </summary>
        public static string ControllerTypeRotaryEncoderText {
            get {
                return ResourceManager.GetString("ControllerTypeRotaryEncoderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet couldn&apos;t start.
        /// </summary>
        public static string CriticalFailureDialogHeaderText {
            get {
                return ResourceManager.GetString("CriticalFailureDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A broken font on your system is preventing EarTrumpet from starting.
        ///
        ///Open [https://eartrumpet.app/jmp/fixfonts] now?.
        /// </summary>
        public static string CriticalFailureFontLookupHelpText {
            get {
                return ResourceManager.GetString("CriticalFailureFontLookupHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deej Control Wizard.
        /// </summary>
        public static string DeejControlWizardText {
            get {
                return ResourceManager.GetString("DeejControlWizardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling.
        /// </summary>
        public static string DeejScaling {
            get {
                return ResourceManager.GetString("DeejScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move / press the hardware control element to be used. -&gt; Captured changes are listed in the table below. -&gt; Select the control to be assigned..
        /// </summary>
        public static string DeejWizardInstructions {
            get {
                return ResourceManager.GetString("DeejWizardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use the default playback device.
        /// </summary>
        public static string DefaultDeviceText {
            get {
                return ResourceManager.GetString("DefaultDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default shortcut.
        /// </summary>
        public static string DefaultHotkeyDescriptionText {
            get {
                return ResourceManager.GetString("DefaultHotkeyDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string DefaultManagementGroupName {
            get {
                return ResourceManager.GetString("DefaultManagementGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string DeleteMidiControlButtonText {
            get {
                return ResourceManager.GetString("DeleteMidiControlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        public static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Selected.
        /// </summary>
        public static string EditMidiControlButtonText {
            get {
                return ResourceManager.GetString("EditMidiControlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand to show all playback devices.
        /// </summary>
        public static string ExpandAccessibleText {
            get {
                return ResourceManager.GetString("ExpandAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a setting.
        /// </summary>
        public static string FindASettingText {
            get {
                return ResourceManager.GetString("FindASettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mixer.
        /// </summary>
        public static string FullWindowTitleText {
            get {
                return ResourceManager.GetString("FullWindowTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control system- and application volumes using a controller hardware (MIDI and deej devices supported)..
        /// </summary>
        public static string HardwareControlInformationText {
            get {
                return ResourceManager.GetString("HardwareControlInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Controls.
        /// </summary>
        public static string HardwareControlsTitle {
            get {
                return ResourceManager.GetString("HardwareControlsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release the selected button and click corresponding &apos;Set&apos; (while released). Then press the selected button and click corresponding &apos;Set&apos; (while pressed)..
        /// </summary>
        public static string HardwareControlWizardMinMaxInstructionsButtonControlType {
            get {
                return ResourceManager.GetString("HardwareControlWizardMinMaxInstructionsButtonControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected control to the minimum value and click corresponding &apos;Set&apos;. Then move the selected control to the maximum value and click corresponding &apos;Set&apos;..
        /// </summary>
        public static string HardwareControlWizardMinMaxInstructionsLinearPotentiometerControlType {
            get {
                return ResourceManager.GetString("HardwareControlWizardMinMaxInstructionsLinearPotentiometerControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the selected rotary control in decreasing direction and click corresponding &apos;Set&apos;. Then turn the selected rotary control in increasing direction and click corresponding &apos;Set&apos;..
        /// </summary>
        public static string HardwareControlWizardMinMaxInstructionsRotaryEncoderControlType {
            get {
                return ResourceManager.GetString("HardwareControlWizardMinMaxInstructionsRotaryEncoderControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushed.
        /// </summary>
        public static string HardwareDeviceButtonControllerScaleMaxValueText {
            get {
                return ResourceManager.GetString("HardwareDeviceButtonControllerScaleMaxValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        public static string HardwareDeviceButtonControllerScaleMinValueText {
            get {
                return ResourceManager.GetString("HardwareDeviceButtonControllerScaleMinValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string HardwareDeviceLinearControllerScaleMaxValueText {
            get {
                return ResourceManager.GetString("HardwareDeviceLinearControllerScaleMaxValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string HardwareDeviceLinearControllerScaleMinValueText {
            get {
                return ResourceManager.GetString("HardwareDeviceLinearControllerScaleMinValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        public static string HardwareDeviceRotaryEncoderControllerScaleMaxValueText {
            get {
                return ResourceManager.GetString("HardwareDeviceRotaryEncoderControllerScaleMaxValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        public static string HardwareDeviceRotaryEncoderControllerScaleMinValueText {
            get {
                return ResourceManager.GetString("HardwareDeviceRotaryEncoderControllerScaleMinValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Edit Hardware Control.
        /// </summary>
        public static string HardwareSettingsText {
            get {
                return ResourceManager.GetString("HardwareSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeButtonText {
            get {
                return ResourceManager.GetString("HomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shortcut.
        /// </summary>
        public static string HotkeyDescriptionText {
            get {
                return ResourceManager.GetString("HotkeyDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete device configuration!.
        /// </summary>
        public static string IncompleteDeviceConfigurationText {
            get {
                return ResourceManager.GetString("IncompleteDeviceConfigurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexed.
        /// </summary>
        public static string IndexedSelection {
            get {
                return ResourceManager.GetString("IndexedSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy settings.
        /// </summary>
        public static string LegacySettingsPageText {
            get {
                return ResourceManager.GetString("LegacySettingsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mixer.
        /// </summary>
        public static string LegacyVolumeMixerText {
            get {
                return ResourceManager.GetString("LegacyVolumeMixerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Control Wizard.
        /// </summary>
        public static string MIDIControlWizardText {
            get {
                return ResourceManager.GetString("MIDIControlWizardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Device.
        /// </summary>
        public static string MidiDevice {
            get {
                return ResourceManager.GetString("MidiDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling.
        /// </summary>
        public static string MidiScaling {
            get {
                return ResourceManager.GetString("MidiScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move / press the hardware control element to be used. -&gt; Captured changes are listed in the table below. -&gt; Select the control to be assigned..
        /// </summary>
        public static string MidiWizardInstructions {
            get {
                return ResourceManager.GetString("MidiWizardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More commands.
        /// </summary>
        public static string MoreCommandsAccessibleText {
            get {
                return ResourceManager.GetString("MoreCommandsAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign this app to a playback device.
        /// </summary>
        public static string MoveButtonAccessibleText {
            get {
                return ResourceManager.GetString("MoveButtonAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        public static string MutedText {
            get {
                return ResourceManager.GetString("MutedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No control selected !.
        /// </summary>
        public static string NoControlSelectedMessageText {
            get {
                return ResourceManager.GetString("NoControlSelectedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It doesn&apos;t look like you have any playback devices..
        /// </summary>
        public static string NoDevicesPanelContent {
            get {
                return ResourceManager.GetString("NoDevicesPanelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet: No playback devices.
        /// </summary>
        public static string NoDeviceTrayText {
            get {
                return ResourceManager.GetString("NoDeviceTrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound settings.
        /// </summary>
        public static string OpenSoundSettingsText {
            get {
                return ResourceManager.GetString("OpenSoundSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback devices.
        /// </summary>
        public static string PlaybackDevicesText {
            get {
                return ResourceManager.GetString("PlaybackDevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewValueText {
            get {
                return ResourceManager.GetString("PreviewValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send crash data to the EarTrumpet team.
        /// </summary>
        public static string PrivacyCheckboxText {
            get {
                return ResourceManager.GetString("PrivacyCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string ProjectADescription {
            get {
                return ResourceManager.GetString("ProjectADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string ProjectATitle {
            get {
                return ResourceManager.GetString("ProjectATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        public static string PublisherText {
            get {
                return ResourceManager.GetString("PublisherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording devices.
        /// </summary>
        public static string RecordingDevicesText {
            get {
                return ResourceManager.GetString("RecordingDevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string SearchBoxNoResultsText {
            get {
                return ResourceManager.GetString("SearchBoxNoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string SetScaleMinMax {
            get {
                return ResourceManager.GetString("SetScaleMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsCategoryTitle {
            get {
                return ResourceManager.GetString("SettingsCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure shortcuts and get help.
        /// </summary>
        public static string SettingsDescriptionText {
            get {
                return ResourceManager.GetString("SettingsDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Taskbar flyout.
        /// </summary>
        public static string SettingsOpenEarTrumpetText {
            get {
                return ResourceManager.GetString("SettingsOpenEarTrumpetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mixer.
        /// </summary>
        public static string SettingsOpenMixerText {
            get {
                return ResourceManager.GetString("SettingsOpenMixerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string SettingsOpenSettingsText {
            get {
                return ResourceManager.GetString("SettingsOpenSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use legacy EarTrumpet icon.
        /// </summary>
        public static string SettingsUseLegacyEarTrumpetIcon {
            get {
                return ResourceManager.GetString("SettingsUseLegacyEarTrumpetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindowText {
            get {
                return ResourceManager.GetString("SettingsWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string ShortcutsPageText {
            get {
                return ResourceManager.GetString("ShortcutsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string SoundsControlPanelText {
            get {
                return ResourceManager.GetString("SoundsControlPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle mute.
        /// </summary>
        public static string ToggleMuteToolTip {
            get {
                return ResourceManager.GetString("ToggleMuteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleSwitchOffText {
            get {
                return ResourceManager.GetString("ToggleSwitchOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleSwitchOnText {
            get {
                return ResourceManager.GetString("ToggleSwitchOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect troubleshooting data.
        /// </summary>
        public static string TroubleshootEarTrumpetText {
            get {
                return ResourceManager.GetString("TroubleshootEarTrumpetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown device selected!.
        /// </summary>
        public static string UnknownDeviceSelectedMessageText {
            get {
                return ResourceManager.GetString("UnknownDeviceSelectedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown device type selected!.
        /// </summary>
        public static string UnknownDeviceTypeSelectedMessageText {
            get {
                return ResourceManager.GetString("UnknownDeviceTypeSelectedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string WebsiteText {
            get {
                return ResourceManager.GetString("WebsiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to EarTrumpet.
        /// </summary>
        public static string WelcomeDialogHeaderText {
            get {
                return ResourceManager.GetString("WelcomeDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Legacy.
        /// </summary>
        public static string WindowsLegacyMenuText {
            get {
                return ResourceManager.GetString("WindowsLegacyMenuText", resourceCulture);
            }
        }
    }
}
