//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarTrumpet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarTrumpet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {Name} add-on.
        /// </summary>
        public static string AboutThisAddonText {
            get {
                return ResourceManager.GetString("AboutThisAddonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string ActionAdditionalText {
            get {
                return ResourceManager.GetString("ActionAdditionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string ActionVerbText {
            get {
                return ResourceManager.GetString("ActionVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add action.
        /// </summary>
        public static string AddActionText {
            get {
                return ResourceManager.GetString("AddActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add condition.
        /// </summary>
        public static string AddConditionText {
            get {
                return ResourceManager.GetString("AddConditionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up hotkeys and automation.
        /// </summary>
        public static string AddonDescriptionText {
            get {
                return ResourceManager.GetString("AddonDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string AddonNameText {
            get {
                return ResourceManager.GetString("AddonNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows Settings.
        /// </summary>
        public static string AddonUninstallButtonText {
            get {
                return ResourceManager.GetString("AddonUninstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This add-on can be removed using the Windows Settings app..
        /// </summary>
        public static string AddonUninstallDescriptionText {
            get {
                return ResourceManager.GetString("AddonUninstallDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string AddonUninstallTitle {
            get {
                return ResourceManager.GetString("AddonUninstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add trigger.
        /// </summary>
        public static string AddTriggerText {
            get {
                return ResourceManager.GetString("AddTriggerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An app session is added, removed, starts playing sound, ....
        /// </summary>
        public static string AppEventTrigger_AddText {
            get {
                return ResourceManager.GetString("AppEventTrigger_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {App} {Option} on {Device}.
        /// </summary>
        public static string AppEventTrigger_LinkText {
            get {
                return ResourceManager.GetString("AppEventTrigger_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{Volume}% volume - {Name}&quot;.
        /// </summary>
        public static string AppOrDeviceFormatAccessibleText {
            get {
                return ResourceManager.GetString("AppOrDeviceFormatAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Muted - {Name}&quot;.
        /// </summary>
        public static string AppOrDeviceMutedFormatAccessibleText {
            get {
                return ResourceManager.GetString("AppOrDeviceMutedFormatAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string AppsListAccessibleText {
            get {
                return ResourceManager.GetString("AppsListAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is added.
        /// </summary>
        public static string AudioAppEventKind_Added {
            get {
                return ResourceManager.GetString("AudioAppEventKind_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is muted.
        /// </summary>
        public static string AudioAppEventKind_Muted {
            get {
                return ResourceManager.GetString("AudioAppEventKind_Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stops playing sound.
        /// </summary>
        public static string AudioAppEventKind_NotPlayingSound {
            get {
                return ResourceManager.GetString("AudioAppEventKind_NotPlayingSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begins playing sound.
        /// </summary>
        public static string AudioAppEventKind_PlayingSound {
            get {
                return ResourceManager.GetString("AudioAppEventKind_PlayingSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is removed.
        /// </summary>
        public static string AudioAppEventKind_Removed {
            get {
                return ResourceManager.GetString("AudioAppEventKind_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is unmuted.
        /// </summary>
        public static string AudioAppEventKind_Unmuted {
            get {
                return ResourceManager.GetString("AudioAppEventKind_Unmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is added.
        /// </summary>
        public static string AudioDeviceEventKind_Added {
            get {
                return ResourceManager.GetString("AudioDeviceEventKind_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to becomes default.
        /// </summary>
        public static string AudioDeviceEventKind_BecomingDefault {
            get {
                return ResourceManager.GetString("AudioDeviceEventKind_BecomingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaves default.
        /// </summary>
        public static string AudioDeviceEventKind_LeavingDefault {
            get {
                return ResourceManager.GetString("AudioDeviceEventKind_LeavingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is removed.
        /// </summary>
        public static string AudioDeviceEventKind_Removed {
            get {
                return ResourceManager.GetString("AudioDeviceEventKind_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string BoolValue_False {
            get {
                return ResourceManager.GetString("BoolValue_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string BoolValue_True {
            get {
                return ResourceManager.GetString("BoolValue_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a device.
        /// </summary>
        public static string ChooseADeviceTitle {
            get {
                return ResourceManager.GetString("ChooseADeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps shown above have played sound recently..
        /// </summary>
        public static string ChooseAnAppHelpText {
            get {
                return ResourceManager.GetString("ChooseAnAppHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an app.
        /// </summary>
        public static string ChooseAnAppTitle {
            get {
                return ResourceManager.GetString("ChooseAnAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonAccessibleText {
            get {
                return ResourceManager.GetString("CloseButtonAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse to show only the default playback device.
        /// </summary>
        public static string CollapseAccessibleText {
            get {
                return ResourceManager.GetString("CollapseAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string ComparisonBoolKind_Is {
            get {
                return ResourceManager.GetString("ComparisonBoolKind_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        public static string ComparisonBoolKind_IsNot {
            get {
                return ResourceManager.GetString("ComparisonBoolKind_IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string ConditionAdditionalText {
            get {
                return ResourceManager.GetString("ConditionAdditionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring a filter is optional but lets you build more advanced actions. All conditions must be true before actions are carried out..
        /// </summary>
        public static string ConditionsHelpText {
            get {
                return ResourceManager.GetString("ConditionsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Filter.
        /// </summary>
        public static string ConditionVerbText {
            get {
                return ResourceManager.GetString("ConditionVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ContextMenuExitTitle {
            get {
                return ResourceManager.GetString("ContextMenuExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playback devices found.
        /// </summary>
        public static string ContextMenuNoDevices {
            get {
                return ResourceManager.GetString("ContextMenuNoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string ContextMenuSendFeedback {
            get {
                return ResourceManager.GetString("ContextMenuSendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I use this action&apos;s context menu item.
        /// </summary>
        public static string ContextMenuTrigger_AddText {
            get {
                return ResourceManager.GetString("ContextMenuTrigger_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I use this action&apos;s context menu item.
        /// </summary>
        public static string ContextMenuTrigger_LinkText {
            get {
                return ResourceManager.GetString("ContextMenuTrigger_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet couldn&apos;t start.
        /// </summary>
        public static string CriticalFailureDialogHeaderText {
            get {
                return ResourceManager.GetString("CriticalFailureDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A broken font on your system is preventing EarTrumpet from starting.
        ///
        ///Open [https://eartrumpet.app/jmp/fixfonts] now?.
        /// </summary>
        public static string CriticalFailureFontLookupHelpText {
            get {
                return ResourceManager.GetString("CriticalFailureFontLookupHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the default playback device is or is not.
        /// </summary>
        public static string DefaultDeviceCondition_AddText {
            get {
                return ResourceManager.GetString("DefaultDeviceCondition_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Device} {Option} the default device.
        /// </summary>
        public static string DefaultDeviceCondition_LinkText {
            get {
                return ResourceManager.GetString("DefaultDeviceCondition_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use the default playback device.
        /// </summary>
        public static string DefaultDeviceText {
            get {
                return ResourceManager.GetString("DefaultDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default shortcut.
        /// </summary>
        public static string DefaultHotkeyDescriptionText {
            get {
                return ResourceManager.GetString("DefaultHotkeyDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string DefaultManagementGroupName {
            get {
                return ResourceManager.GetString("DefaultManagementGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default playback device.
        /// </summary>
        public static string DefaultPlaybackDeviceText {
            get {
                return ResourceManager.GetString("DefaultPlaybackDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DeleteActionDialogNoText {
            get {
                return ResourceManager.GetString("DeleteActionDialogNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this action?.
        /// </summary>
        public static string DeleteActionDialogText {
            get {
                return ResourceManager.GetString("DeleteActionDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteActionDialogTitle {
            get {
                return ResourceManager.GetString("DeleteActionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteActionDialogYesText {
            get {
                return ResourceManager.GetString("DeleteActionDialogYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An audio device is added, removed, set as default, ....
        /// </summary>
        public static string DeviceEventTrigger_AddText {
            get {
                return ResourceManager.GetString("DeviceEventTrigger_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Device} {Option}.
        /// </summary>
        public static string DeviceEventTrigger_LinkText {
            get {
                return ResourceManager.GetString("DeviceEventTrigger_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends.
        /// </summary>
        public static string EarTrumpetEventKind_Shutdown {
            get {
                return ResourceManager.GetString("EarTrumpetEventKind_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts.
        /// </summary>
        public static string EarTrumpetEventKind_Startup {
            get {
                return ResourceManager.GetString("EarTrumpetEventKind_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet Actions XML.
        /// </summary>
        public static string EtaXmlFileText {
            get {
                return ResourceManager.GetString("EtaXmlFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet starts or ends.
        /// </summary>
        public static string EventTrigger_AddText {
            get {
                return ResourceManager.GetString("EventTrigger_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  EarTrumpet {Option}.
        /// </summary>
        public static string EventTrigger_LinkText {
            get {
                return ResourceManager.GetString("EventTrigger_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every app.
        /// </summary>
        public static string EveryAppText {
            get {
                return ResourceManager.GetString("EveryAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand to show all playback devices.
        /// </summary>
        public static string ExpandAccessibleText {
            get {
                return ResourceManager.GetString("ExpandAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportHeaderText {
            get {
                return ResourceManager.GetString("ExportHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a copy of your actions to a file..
        /// </summary>
        public static string ExportHelpText {
            get {
                return ResourceManager.GetString("ExportHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse settings.
        /// </summary>
        public static string MouseSettingsPageText {
            get {
                return ResourceManager.GetString("MouseSettingsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a setting.
        /// </summary>
        public static string FindASettingText {
            get {
                return ResourceManager.GetString("FindASettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground app.
        /// </summary>
        public static string ForegroundAppText {
            get {
                return ResourceManager.GetString("ForegroundAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mixer.
        /// </summary>
        public static string FullWindowTitleText {
            get {
                return ResourceManager.GetString("FullWindowTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeButtonText {
            get {
                return ResourceManager.GetString("HomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shortcut.
        /// </summary>
        public static string HotkeyDescriptionText {
            get {
                return ResourceManager.GetString("HotkeyDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hotkey is typed.
        /// </summary>
        public static string HotkeyTrigger_AddText {
            get {
                return ResourceManager.GetString("HotkeyTrigger_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (choose a hotkey).
        /// </summary>
        public static string HotkeyTrigger_EmptyText {
            get {
                return ResourceManager.GetString("HotkeyTrigger_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Hotkey} is typed.
        /// </summary>
        public static string HotkeyTrigger_LinkText {
            get {
                return ResourceManager.GetString("HotkeyTrigger_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import and export.
        /// </summary>
        public static string ImportAndExportTitle {
            get {
                return ResourceManager.GetString("ImportAndExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportHeaderText {
            get {
                return ResourceManager.GetString("ImportHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore a copy of your actions from a file..
        /// </summary>
        public static string ImportHelpText {
            get {
                return ResourceManager.GetString("ImportHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LeavingPageDialogNoText {
            get {
                return ResourceManager.GetString("LeavingPageDialogNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave without saving?.
        /// </summary>
        public static string LeavingPageDialogText {
            get {
                return ResourceManager.GetString("LeavingPageDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LeavingPageDialogTitle {
            get {
                return ResourceManager.GetString("LeavingPageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string LeavingPageDialogYesText {
            get {
                return ResourceManager.GetString("LeavingPageDialogYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy settings.
        /// </summary>
        public static string LegacySettingsPageText {
            get {
                return ResourceManager.GetString("LegacySettingsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mixer.
        /// </summary>
        public static string LegacyVolumeMixerText {
            get {
                return ResourceManager.GetString("LegacyVolumeMixerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More commands.
        /// </summary>
        public static string MoreCommandsAccessibleText {
            get {
                return ResourceManager.GetString("MoreCommandsAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign this app to a playback device.
        /// </summary>
        public static string MoveButtonAccessibleText {
            get {
                return ResourceManager.GetString("MoveButtonAccessibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        public static string MutedText {
            get {
                return ResourceManager.GetString("MutedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string MuteKind_Mute {
            get {
                return ResourceManager.GetString("MuteKind_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle mute.
        /// </summary>
        public static string MuteKind_ToggleMute {
            get {
                return ResourceManager.GetString("MuteKind_ToggleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        public static string MuteKind_Unmute {
            get {
                return ResourceManager.GetString("MuteKind_Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MyActionsText {
            get {
                return ResourceManager.GetString("MyActionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New action.
        /// </summary>
        public static string NewActionText {
            get {
                return ResourceManager.GetString("NewActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It doesn&apos;t look like you have any playback devices..
        /// </summary>
        public static string NoDevicesPanelContent {
            get {
                return ResourceManager.GetString("NoDevicesPanelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet: No playback devices.
        /// </summary>
        public static string NoDeviceTrayText {
            get {
                return ResourceManager.GetString("NoDeviceTrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App volume and device preferences.
        /// </summary>
        public static string OpenAppsVolume_Windows10_Text {
            get {
                return ResourceManager.GetString("OpenAppsVolume_Windows10_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume mixer.
        /// </summary>
        public static string OpenAppsVolume_Windows11_Text {
            get {
                return ResourceManager.GetString("OpenAppsVolume_Windows11_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound settings.
        /// </summary>
        public static string OpenSoundSettingsText {
            get {
                return ResourceManager.GetString("OpenSoundSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (optional).
        /// </summary>
        public static string OptionalText {
            get {
                return ResourceManager.GetString("OptionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string PlaybackDeviceGroupText {
            get {
                return ResourceManager.GetString("PlaybackDeviceGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback devices.
        /// </summary>
        public static string PlaybackDevicesText {
            get {
                return ResourceManager.GetString("PlaybackDevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send crash data to the EarTrumpet team.
        /// </summary>
        public static string PrivacyCheckboxText {
            get {
                return ResourceManager.GetString("PrivacyCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a process is running or not.
        /// </summary>
        public static string ProcessCondition_AddText {
            get {
                return ResourceManager.GetString("ProcessCondition_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (enter a process name).
        /// </summary>
        public static string ProcessCondition_EmptyText {
            get {
                return ResourceManager.GetString("ProcessCondition_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When {Text} {Option}.
        /// </summary>
        public static string ProcessCondition_LinkText {
            get {
                return ResourceManager.GetString("ProcessCondition_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name (e.g. notepad).
        /// </summary>
        public static string ProcessCondition_PromptText {
            get {
                return ResourceManager.GetString("ProcessCondition_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts.
        /// </summary>
        public static string ProcessEventKind_Start {
            get {
                return ResourceManager.GetString("ProcessEventKind_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends.
        /// </summary>
        public static string ProcessEventKind_Stop {
            get {
                return ResourceManager.GetString("ProcessEventKind_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not running.
        /// </summary>
        public static string ProcessStateKind_NotRunning {
            get {
                return ResourceManager.GetString("ProcessStateKind_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is running.
        /// </summary>
        public static string ProcessStateKind_Running {
            get {
                return ResourceManager.GetString("ProcessStateKind_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A process starts or ends.
        /// </summary>
        public static string ProcessTrigger_AddText {
            get {
                return ResourceManager.GetString("ProcessTrigger_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (enter a process name).
        /// </summary>
        public static string ProcessTrigger_EmptyText {
            get {
                return ResourceManager.GetString("ProcessTrigger_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When {Text} {Option}.
        /// </summary>
        public static string ProcessTrigger_LinkText {
            get {
                return ResourceManager.GetString("ProcessTrigger_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name (e.g. notepad).
        /// </summary>
        public static string ProcessTrigger_PromptText {
            get {
                return ResourceManager.GetString("ProcessTrigger_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string ProjectADescription {
            get {
                return ResourceManager.GetString("ProjectADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string ProjectATitle {
            get {
                return ResourceManager.GetString("ProjectATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        public static string PublisherText {
            get {
                return ResourceManager.GetString("PublisherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string RecordingDeviceGroupText {
            get {
                return ResourceManager.GetString("RecordingDeviceGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording devices.
        /// </summary>
        public static string RecordingDevicesText {
            get {
                return ResourceManager.GetString("RecordingDevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this action.
        /// </summary>
        public static string RemoveActionButtonText {
            get {
                return ResourceManager.GetString("RemoveActionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cannot be undone..
        /// </summary>
        public static string RemoveActionDescriptionText {
            get {
                return ResourceManager.GetString("RemoveActionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove action.
        /// </summary>
        public static string RemoveActionHeadingText {
            get {
                return ResourceManager.GetString("RemoveActionHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveButtonAccessibleName {
            get {
                return ResourceManager.GetString("RemoveButtonAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveText {
            get {
                return ResourceManager.GetString("RemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (required).
        /// </summary>
        public static string RequiredText {
            get {
                return ResourceManager.GetString("RequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string SearchBoxNoResultsText {
            get {
                return ResourceManager.GetString("SearchBoxNoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute or unmute an app.
        /// </summary>
        public static string SetAppMuteAction_AddText {
            get {
                return ResourceManager.GetString("SetAppMuteAction_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Option} {App} on {Device}.
        /// </summary>
        public static string SetAppMuteAction_LinkText {
            get {
                return ResourceManager.GetString("SetAppMuteAction_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the volume of an app.
        /// </summary>
        public static string SetAppVolumeAction_AddText {
            get {
                return ResourceManager.GetString("SetAppVolumeAction_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Option} {App} volume to {Volume} on {Device}.
        /// </summary>
        public static string SetAppVolumeAction_LinkText {
            get {
                return ResourceManager.GetString("SetAppVolumeAction_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Option} {App} volume by {Volume} on {Device}.
        /// </summary>
        public static string SetAppVolumeAction_LinkTextIncrement {
            get {
                return ResourceManager.GetString("SetAppVolumeAction_LinkTextIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the default playback device.
        /// </summary>
        public static string SetDefaultDeviceAction_AddText {
            get {
                return ResourceManager.GetString("SetDefaultDeviceAction_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {Device} as playback default.
        /// </summary>
        public static string SetDefaultDeviceAction_LinkText {
            get {
                return ResourceManager.GetString("SetDefaultDeviceAction_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute or unmute a device.
        /// </summary>
        public static string SetDeviceMuteAction_AddText {
            get {
                return ResourceManager.GetString("SetDeviceMuteAction_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Option} {Device}.
        /// </summary>
        public static string SetDeviceMuteAction_LinkText {
            get {
                return ResourceManager.GetString("SetDeviceMuteAction_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Option} on {Device}.
        /// </summary>
        public static string SetDeviceMuteAction_LinkTextToggle {
            get {
                return ResourceManager.GetString("SetDeviceMuteAction_LinkTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a device volume.
        /// </summary>
        public static string SetDeviceVolumeAction_AddText {
            get {
                return ResourceManager.GetString("SetDeviceVolumeAction_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Option} {Device} volume to {Volume}.
        /// </summary>
        public static string SetDeviceVolumeAction_LinkText {
            get {
                return ResourceManager.GetString("SetDeviceVolumeAction_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Option} {Device} volume by {Volume}.
        /// </summary>
        public static string SetDeviceVolumeAction_LinkTextIncrement {
            get {
                return ResourceManager.GetString("SetDeviceVolumeAction_LinkTextIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease volume for all devices.
        /// </summary>
        public static string SettingsAbsoluteVolumeDownText {
            get {
                return ResourceManager.GetString("SettingsAbsoluteVolumeDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase volume for all devices.
        /// </summary>
        public static string SettingsAbsoluteVolumeUpText {
            get {
                return ResourceManager.GetString("SettingsAbsoluteVolumeUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsCategoryTitle {
            get {
                return ResourceManager.GetString("SettingsCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure shortcuts and get help.
        /// </summary>
        public static string SettingsDescriptionText {
            get {
                return ResourceManager.GetString("SettingsDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Taskbar flyout.
        /// </summary>
        public static string SettingsOpenEarTrumpetText {
            get {
                return ResourceManager.GetString("SettingsOpenEarTrumpetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mixer.
        /// </summary>
        public static string SettingsOpenMixerText {
            get {
                return ResourceManager.GetString("SettingsOpenMixerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string SettingsOpenSettingsText {
            get {
                return ResourceManager.GetString("SettingsOpenSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarTrumpet Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the scroll wheel to change volume while the flyout is open.
        /// </summary>
        public static string SettingsUseGlobalMouseWheelHook {
            get {
                return ResourceManager.GetString("SettingsUseGlobalMouseWheelHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use legacy EarTrumpet icon.
        /// </summary>
        public static string SettingsUseLegacyEarTrumpetIcon {
            get {
                return ResourceManager.GetString("SettingsUseLegacyEarTrumpetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindowText {
            get {
                return ResourceManager.GetString("SettingsWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a local variable.
        /// </summary>
        public static string SetVariableAction_AddText {
            get {
                return ResourceManager.GetString("SetVariableAction_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (set variable name).
        /// </summary>
        public static string SetVariableAction_EmptyText {
            get {
                return ResourceManager.GetString("SetVariableAction_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set variable {Text} to {Option}.
        /// </summary>
        public static string SetVariableAction_LinkText {
            get {
                return ResourceManager.GetString("SetVariableAction_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a variable name (e.g. isInGameMode).
        /// </summary>
        public static string SetVariableAction_PromptText {
            get {
                return ResourceManager.GetString("SetVariableAction_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement.
        /// </summary>
        public static string SetVolumeKind_Decrement {
            get {
                return ResourceManager.GetString("SetVolumeKind_Decrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment.
        /// </summary>
        public static string SetVolumeKind_Increment {
            get {
                return ResourceManager.GetString("SetVolumeKind_Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string SetVolumeKind_Set {
            get {
                return ResourceManager.GetString("SetVolumeKind_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string ShortcutsPageText {
            get {
                return ResourceManager.GetString("ShortcutsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string SoundsControlPanelText {
            get {
                return ResourceManager.GetString("SoundsControlPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle mute.
        /// </summary>
        public static string ToggleMuteToolTip {
            get {
                return ResourceManager.GetString("ToggleMuteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleSwitchOffText {
            get {
                return ResourceManager.GetString("ToggleSwitchOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleSwitchOnText {
            get {
                return ResourceManager.GetString("ToggleSwitchOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ToolbarDeleteText {
            get {
                return ResourceManager.GetString("ToolbarDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ToolbarEditText {
            get {
                return ResourceManager.GetString("ToolbarEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolbarSaveText {
            get {
                return ResourceManager.GetString("ToolbarSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string TriggerAdditionalText {
            get {
                return ResourceManager.GetString("TriggerAdditionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string TriggerVerbText {
            get {
                return ResourceManager.GetString("TriggerVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect troubleshooting data.
        /// </summary>
        public static string TroubleshootEarTrumpetText {
            get {
                return ResourceManager.GetString("TroubleshootEarTrumpetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a local variable is true or false.
        /// </summary>
        public static string VariableCondition_AddText {
            get {
                return ResourceManager.GetString("VariableCondition_AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (enter a variable name).
        /// </summary>
        public static string VariableCondition_EmptyText {
            get {
                return ResourceManager.GetString("VariableCondition_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {Text} is {Option}.
        /// </summary>
        public static string VariableCondition_LinkText {
            get {
                return ResourceManager.GetString("VariableCondition_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a variable name (e.g. isInGameMode).
        /// </summary>
        public static string VariableCondition_PromptText {
            get {
                return ResourceManager.GetString("VariableCondition_PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string WebsiteText {
            get {
                return ResourceManager.GetString("WebsiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to EarTrumpet.
        /// </summary>
        public static string WelcomeDialogHeaderText {
            get {
                return ResourceManager.GetString("WelcomeDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Legacy.
        /// </summary>
        public static string WindowsLegacyMenuText {
            get {
                return ResourceManager.GetString("WindowsLegacyMenuText", resourceCulture);
            }
        }
    }
}
