name: Configure Nuspec
inputs:
  nuspec:
    required: true
  version:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure Nuspec
      shell: pwsh
      run: |
        $Version = [Version](Get-Content "${{ inputs.version }}")
        $NuspecPath = "${{ inputs.nuspec }}"

        $nuspec = [xml](Get-Content -Path $NuspecPath)
        $nuspec.package.metadata.version = $Version
        $nuspec.Save($NuspecPath)
